# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
# IP: The module: 'pcie_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_jtag.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie_7x_0_jtag || ORIG_REF_NAME==pcie_7x_0_jtag} -quiet] -quiet

# XDC: d:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/pcie_7x_0/ip_0/constraints/jtag_axi.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0_jtag || ORIG_REF_NAME==pcie_7x_0_jtag} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/pcie_7x_0/source/ip_xilinx_pcie_2_1_7x_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.srcs/sources_1/ip/pcie_7x_0/pcie_7x_0.xci
# IP: The module: 'pcie_7x_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/pcie_7x_0/ip_0/pcie_7x_0_jtag.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pcie_7x_0_jtag || ORIG_REF_NAME==pcie_7x_0_jtag} -quiet] -quiet

# XDC: d:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/pcie_7x_0/ip_0/constraints/jtag_axi.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie_7x_0_jtag || ORIG_REF_NAME==pcie_7x_0_jtag} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/pcie_7x_0/source/pcie_7x_0-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/pcie_7x_0/source/ip_xilinx_pcie_2_1_7x_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/code/pcileech-fpga/PCIeSquirrel/pcileech_squirrel/pcileech_squirrel.gen/sources_1/ip/pcie_7x_0/synth/pcie_7x_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie_7x_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
